// No dependencies. Runs the actual inline app script with a minimal DOM adapter.
// Covers state, rendering, and event handlers; does not replace browser/layout testing.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
let source=fs.readFileSync(__dirname+'/index.html','utf8').split('<script>')[1].split('</script>')[0];
source=source.replace('render()})();','render();globalThis.app={get state(){return s},missingWork,correct,expected,setRoom(n){room=n;render()}}})();');
const base=()=>({completionVersion:1,mode:'giants',name:'Demo',class:'Test',object:'Box',materials:'Cardboard',plan:'Fold and join',structure:'Rectangular faces',unit:'cm',factor:2,m:Array.from({length:8},(_,i)=>({n:'Edge '+i,o:'3',p:'6',check:true})),build:Array(5).fill(true),before:'Sketch',during:'Teacher observation',after:'Model on table',difference:'None; dimensions match',proof:'Two dimensions double',hardest:'Joining tabs',proud:'Proportions',validate:Array(5).fill(true)});
function load(saved){
 const nodes=new Map();let stored=JSON.stringify(saved);
 const node=selector=>{if(!nodes.has(selector)){const match=selector.match(/data-(\w+)="(.*?)"/);nodes.set(selector,{innerHTML:'',textContent:'',value:'',checked:false,hidden:false,dataset:match?{[match[1]]:match[2]}:{},focus(){},remove(){this.removed=true;}});}return nodes.get(selector);};
 const document={querySelector:node,querySelectorAll(selector){const key=selector.match(/data-(\w+)/)?.[1];if(!key)return [];return (key==='mode'?['giants','ants']:Array.from({length:['n','o','p','c'].includes(key)?8:key==='r'?7:5},(_,i)=>String(i))).map(i=>node(`[data-${key}="${i}"]`));}};
 const ctx={document,localStorage:{getItem:()=>stored,setItem:(_,value)=>stored=value}};vm.createContext(ctx);vm.runInContext(source,ctx);
 return {app:ctx.app,node,stored:()=>JSON.parse(stored),keep(){ctx.app.setRoom(6);return node('#view').innerHTML;},input(selector,value){let e=node(selector);e.value=value;e.oninput();},change(selector,value){let e=node(selector);e.value=value;e.checked=!!value;e.onchange({target:e});}};
}
let assertions=0;function check(condition){assert(condition);assertions++;}let groups=0;
function test(name,fn){fn();groups++;console.log('PASS '+name);}
test('Correctness recomputed instead of trusting check flag',()=>{let s=base();s.m.forEach(x=>x.p='999');let t=load(s);check(t.keep().includes('mission incomplete'));check(t.app.missingWork().length===8);for(const [key,value] of [['o',''],['o','0'],['o','-1'],['o','Infinity'],['p',''],['p','-1'],['p','Infinity'],['p','6.01'],['n','   ']]){s=base();s.m[0][key]=value;t=load(s);check(t.keep().includes('mission incomplete'));}});
test('All required fields and checklist items gate completion',()=>{for(const key of ['object','materials','plan','structure','before','during','after','difference','proof','hardest','proud']){let s=base();s[key]='   ';check(load(s).keep().includes('mission incomplete'));}for(const key of ['build','validate'])for(let i=0;i<5;i++){let s=base();s[key][i]=false;check(load(s).keep().includes('mission incomplete'));}});
test('All learner text changes invalidate approvals and retain new content',()=>{for(const key of ['name','class','object','materials','plan','structure','before','during','after','difference','proof','hardest','proud']){let t=load(base());t.input('#'+key,'Revised');check(t.app.state.validate.every(x=>!x));check(t.stored()[key]==='Revised');check(t.keep().includes('Work changed'));}let t=load(base());t.input('#name','Demo');check(t.app.state.validate.every(Boolean));});
test('Measurement edits reset their check and clear stale feedback',()=>{for(const key of ['n','o','p']){let t=load(base());t.input(`[data-${key}="0"]`,key==='n'?'New edge':'7');check(t.app.state.m[0].check===false);check(t.app.state.validate.every(x=>!x));check(t.node('[data-result="0"]').removed===true);}});
test('World, factor and units require fresh checks and approval',()=>{for(const kind of ['mode','factor','unit']){let t=load(base());if(kind==='mode')t.node('[data-mode="ants"]').onclick();else t.change('#'+kind,kind==='factor'?'3':'mm');check(t.app.state.m.every(x=>!x.check));check(t.stored().validate.every(x=>!x));}let t=load(base());t.node('[data-mode="giants"]').onclick();check(t.app.state.validate.every(Boolean));});
test('Build edit invalidates review',()=>{let t=load(base());t.change('[data-b="0"]',false);check(t.app.state.validate.every(x=>!x));check(t.keep().includes('complete all five build'));});
test('Teacher checks update credential immediately, revoke it, and persist',()=>{let s=base();s.validate=Array(5).fill(false);let t=load(s);t.keep();for(let i=0;i<5;i++)t.change(`[data-v="${i}"]`,true);check(!t.node('#view').innerHTML.includes('mission incomplete'));check(!load(t.stored()).keep().includes('mission incomplete'));t.change('[data-v="4"]',false);check(t.node('#view').innerHTML.includes('mission incomplete'));s=base();s.proof='';s.validate=Array(5).fill(false);t=load(s);t.change('[data-v="0"]',true);check(t.app.state.validate[0]===false);check(t.keep().includes('disabled'));});
test('Legacy migration preserves work and invalidates old check/approval',()=>{let s=base();delete s.completionVersion;let t=load(s);check(t.app.state.object==='Box');check(t.app.state.m[0].p==='6');check(t.app.state.m.every(x=>!x.check));check(t.app.state.validate.every(x=>!x));check(t.stored().completionVersion===1);});
test('Ants mode, rounding boundary, correct retry, and actionable next steps',()=>{let s=base();s.mode='ants';s.factor=3;s.m.forEach(x=>{x.o='1';x.p='0.33';x.check=false;});s.validate=Array(5).fill(false);let t=load(s);check(t.keep().includes('data-go="3"'));t.node('[data-go="3"]').onclick();check(t.node('#view').innerHTML.includes('A · Alter'));for(let i=0;i<8;i++)t.node(`[data-c="${i}"]`).onclick();check(t.app.missingWork().length===0);t.input('[data-p="0"]','0.34');t.node('[data-c="0"]').onclick();check(t.app.missingWork().length===1);t.input('[data-p="0"]','0.33');t.node('[data-c="0"]').onclick();check(t.app.missingWork().length===0);});
console.log(`${groups} groups passed; ${assertions} assertions. Browser and visual checks are separate.`);
